# Generated by Django 5.0.3 on 2024-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
